site_url: http://log.winsos.net
deploy_to: yves@www.winsos.lan:/var/www/log/
title: eunomie's log
name: Yves Brissaud
twitter_site: _crev_
twitter_creator: _crev_
default_description: My personal weblog
accounts:
    twitter: https://twitter.com/_crev_
    github: http://github.com/eunomie
    linkedin: http://fr.linkedin.com/in/yvesbrissaud
assets:
    css: [application, cv, "doing-things-for-fun", "beautiful-things", "think-big", creativity, future]
    js: [application]
